const assert=require('node:assert/strict');const {test}=require('node:test');const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const {stripTypeScriptTypes}=require('node:module');
const root=path.join(__dirname,'../../artifacts/mobile');
function load(file,names,globals={}){const exports={};const src=fs.readFileSync(path.join(root,file),'utf8').replace(/^import .*\n/gm,'').replace(/^export /gm,'');vm.runInNewContext(stripTypeScriptTypes(src,{mode:'transform'})+'\nObject.assign(exports,{'+names.join(',')+'});',{exports,...globals});return exports;}
const model=load('lib/features/messages/model.ts',['mergePrivateMessages','canRemoveForEveryone','privateMessagePopover']);
const msg=(id,sender='a',created='2026-10-09T10:00:00Z')=>({id,sender_id:sender,created_at:created,conversation_id:'room',text:id,read_by_other:false});
test('the echoed realtime row replaces the confirmed send instead of duplicating it',()=>{const m=msg('one');const rows=model.mergePrivateMessages([m],[{...m,read_by_other:true}]);assert.equal(rows.length,1);assert.equal(rows[0].read_by_other,true);});
test('history and concurrent replies retain chronological order with stable timestamp ties',()=>{const rows=model.mergePrivateMessages([msg('b'),msg('d','a','2026-10-09T10:00:02Z')],[msg('a'),msg('c','b','2026-10-09T10:00:01Z')]);assert.equal(rows.map(r=>r.id).join(','),'a,b,c,d');});
test('removed message content disappears while other participants messages remain',()=>{const rows=model.mergePrivateMessages([msg('mine'),msg('theirs','b')],[{...msg('mine'),text:'',deleted_at:'2026-10-09T11:00:00Z'}]);assert.equal(rows.length,1);assert.equal(rows[0].id,'theirs');});
test('remove for everyone is offered only for a nonempty selection entirely authored by me',()=>{assert.equal(model.canRemoveForEveryone([], 'a'),false);assert.equal(model.canRemoveForEveryone([msg('one'),msg('two')],'a'),true);assert.equal(model.canRemoveForEveryone([msg('one'),msg('two','b')],'a'),false);});
test('popover fits narrow and keyboard-reduced screens and prefers the space above a message',()=>{for(const width of [320,360,575]){const p=model.privateMessagePopover({x:width-120,y:410,width:110,height:50},width,700,24,230);assert.ok(p.left>=16&&p.left+p.width<=width-16);assert.ok(p.top+p.maxHeight<=410);assert.ok(p.maxHeight>=180);}const p=model.privateMessagePopover({x:220,y:100,width:90,height:40},320,280,24,440);assert.ok(p.top>=24&&p.top+p.maxHeight<=264);assert.ok(p.maxHeight<440);});
function service(db){return load('lib/features/messages/services/private-messages.ts',['sendPrivateMessage','readPrivateInbox','readPrivateMessages','removePrivateMessages'],{supabase:db});}
test('a lost send response is verified by id and preserves the same message on retry',async()=>{const draft={id:'one',conversation_id:'room',sender_id:'a',text:'hello'};let calls=0;const db={rpc:async(name,args)=>{assert.equal(name,'send_private_message');assert.equal(args.p_id,'one');calls++;return{data:null,error:new Error('response lost')};},from:()=>({select(){return this;},eq(){return this;},maybeSingle:async()=>({data:{...draft,created_at:'now'}})})};const sent=await service(db).sendPrivateMessage(draft);assert.equal(sent.id,'one');assert.equal(calls,1);});
test('send failure does not pretend success or accept a different author',async()=>{const draft={id:'one',conversation_id:'room',sender_id:'a',text:'hello'};const db={rpc:async()=>({error:{}}),from:()=>({select(){return this;},eq(){return this;},maybeSingle:async()=>({data:{...draft,sender_id:'b'}})})};await assert.rejects(service(db).sendPrivateMessage(draft),/Conservamos tu texto/);});
test('inbox errors are surfaced rather than turned into an empty inbox',async()=>{const q={select(){return this;},order(){return this;},limit:async()=>({data:null,error:{message:'offline'}})};await assert.rejects(service({from:name=>{assert.equal(name,'private_conversation_inbox');return q;}}).readPrivateInbox(),/conversaciones/);});
test('history pagination includes an id tie-breaker instead of skipping simultaneous messages',async()=>{let filter;const q={select(){return this;},eq(){return this;},order(){return this;},limit(){return this;},or(value){filter=value;return this;},then(resolve){resolve({data:[],error:null});}};await service({from:()=>q}).readPrivateMessages('room',{created_at:'2026-10-09T10:00:00Z',id:'uuid'});assert.match(filter,/created_at\.eq.*id\.lt\.uuid/);});
test('delete confirmation failure is surfaced and all selection uses its captured cutoff',async()=>{let args;const db={rpc:async(name,value)=>{assert.equal(name,'remove_private_messages');args=value;return{data:null,error:{}};}};await assert.rejects(service(db).removePrivateMessages('room',[],false,'2026-10-09T10:00:00Z'));assert.equal(args.p_before,'2026-10-09T10:00:00Z');assert.equal(args.p_for_all,false);});
