const assert=require('node:assert/strict');const {test}=require('node:test');const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const ts=require('typescript');const {stripTypeScriptTypes}=require('node:module');
const root=path.join(__dirname,'../../artifacts/mobile');const exportsObject={};
vm.runInNewContext(stripTypeScriptTypes(fs.readFileSync(path.join(root,'lib/features/profile/presentation.ts'),'utf8').replace(/^export /gm,''),{mode:'transform'})+'\nObject.assign(exports,{publicationTileSize,connectionIds});',{exports:exportsObject});
test('three visible publication cards fit narrow, phone and tablet widths with stable gutters',()=>{for(const width of [280,320,360,393,575,800]){const tile=exportsObject.publicationTileSize(width);assert.ok(tile.width>0&&tile.height>tile.width);assert.ok(tile.width*3+12+20<=width);assert.ok(width-(tile.width*3+12+20)<3);}});
test('followers, following and mutual friends are distinct and exclude self',()=>{const ids=exportsObject.connectionIds([{follower_id:'me',following_id:'a'},{follower_id:'a',following_id:'me'},{follower_id:'b',following_id:'me'},{follower_id:'me',following_id:'c'},{follower_id:'me',following_id:'me'}],'me');assert.equal(ids.friends.join(','),'a');assert.equal(ids.followers.join(','),'a,b');assert.equal(ids.following.join(','),'a,c');});
test('unfollowing immediately changes the mutual-friends membership',()=>{const ids=exportsObject.connectionIds([{follower_id:'a',following_id:'me'}],'me');assert.equal(ids.friends.length,0);assert.equal(ids.followers.length,1);assert.equal(ids.following.length,0);});
function videoInfo(){const exp={};const element=(type,props,...children)=>({type,props:{...props,children}});const react={createElement:element,useRef:current=>({current}),useEffect(){}};const modules={react,'react-native':{Animated:{Value:class{},View:'AnimatedView',Text:'AnimatedText'},Image:'Image',Text:'Text',TouchableOpacity:'Button',View:'View',StyleSheet:{create:x=>x}},'@expo/vector-icons':{Feather:'Icon'},'expo-router':{router:{}},'../context/AuthContext':{useAuth:()=>({user:{id:'me'}})},'../lib/features/auth/services/registrationBridge':{requestRegistration(){}},'../lib/supabase':{supabase:{}}};const src=ts.transpileModule(fs.readFileSync(path.join(root,'components/VideoInfo.tsx'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText;vm.runInNewContext(src,{exports:exp,require:name=>{if(name.includes('jsx-runtime'))return{jsx:(t,p)=>({type:t,props:p}),jsxs:(t,p)=>({type:t,props:p})};if(!(name in modules))throw Error(name);return modules[name];}});return exp.default;}
function nodes(n){return !n||typeof n!=='object'?[]:Array.isArray(n)?n.flatMap(nodes):[n,...nodes(n.props?.children)];}
test('own video has no Follow control, other creators reflect following and pending state',()=>{const Info=videoInfo(),follow=()=>{};const base={creator:'me',creatorHandle:'@me',creatorAvatar:'photo',caption:'',song:'sound',onFollow:follow,isFollowing:false};assert.equal(nodes(Info({...base,isOwner:true})).filter(n=>n.props?.onPress===follow).length,0);let b=nodes(Info({...base,isOwner:false,followPending:true})).find(n=>n.props?.onPress===follow);assert.equal(b.props.disabled,true);assert.ok(JSON.stringify(nodes(Info({...base,isFollowing:true}))).includes('Siguiendo'));});
