const assert=require('node:assert/strict');const {test}=require('node:test');const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');const {stripTypeScriptTypes}=require('node:module');
const source=fs.readFileSync(path.join(__dirname,'../../artifacts/mobile/lib/features/feed/publications.ts'),'utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'');const exportsObject={};vm.runInNewContext(stripTypeScriptTypes(source,{mode:'transform'})+'\nexports.read=readPublishedFeedPage;',{exports:exportsObject});
const read=exportsObject.read;
function client(rows,error=null){let calls=0;return {get calls(){return calls;},from(table){assert.equal(table,'videos');calls++;let authors;const q={select:()=>q,order:()=>q,in:(column,ids)=>{assert.equal(column,'user_id');authors=ids;return q;},range:async(start,end)=>({data:rows.filter(r=>!authors||authors.includes(r.user_id)).slice(start,end+1),error})};return q;}};}
const rows=[...Array.from({length:18},(_,i)=>({id:'public-'+i,user_id:'public',media_type:'video'})),{id:'my-video',user_id:'followed-author',media_type:'video'},{id:'my-photo',user_id:'followed-author',media_type:'image'}];
test('For You includes newly published video and photo rows',async()=>{const result=await read(client([rows[18],rows[19],...rows]),0);assert.equal(result[0].id,'my-video');assert.equal(result[1].id,'my-photo');});
test('Following retrieves followed authors before pagination even when absent from newest public page',async()=>{const result=await read(client(rows),0,['followed-author']);assert.equal(result.length,2);assert.equal(result[0].id,'my-video');assert.equal(result[1].id,'my-photo');});
test('no followed authors produces a real empty feed without an unfiltered query',async()=>{const db=client(rows);assert.equal((await read(db,0,[])).length,0);assert.equal(db.calls,0);});
test('Following excludes an author after unfollow and never includes own posts by default',async()=>{assert.equal((await read(client(rows),0,['different-author'])).length,0);});
test('query errors are surfaced instead of appearing as a successful empty feed',async()=>{await assert.rejects(read(client(rows,new Error('offline')),0),/offline/);});
