-- #24: allow notifications generated by private messages.
alter table public.notifications drop constraint if exists notifications_type_check;

alter table public.notifications
add constraint notifications_type_check
check (type = any (array[
  'like',
  'comment',
  'follow',
  'mention',
  'system',
  'message'
]::text[]));
